#!/bin/sh
set -e
# Automatically added by dh_installdeb/12.10ubuntu1
dpkg-maintscript-helper rm_conffile /etc/redis/redis-server.post-down.d/00_example 4:4.0.2-3\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/redis/redis-server.post-up.d/00_example 4:4.0.2-3\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/redis/redis-server.pre-down.d/00_example 4:4.0.2-3\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/redis/redis-server.pre-up.d/00_example 4:4.0.2-3\~ -- "$@"
# End automatically added section
